FROM python:3.12-slim

WORKDIR /app

# Installation du strict nécessaire pour compiler certaines roues Python si besoin
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copie et installation des bibliothèques Python
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copie du code source
COPY . .

# Port Streamlit
EXPOSE 8501

# Lancement robuste via le module python
CMD ["python", "-m", "streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]